app:
  TITLE: "AppTitle"
  HOST: "0.0.0.0"
  PORT: 8000
  DEBUG: true
  LOG_LEVEL: "DEBUG"

db:
  USERNAME: "postgres"
  DATABASE: "baseapp_db"
  HOST: "localhost"
  PORT: 5432
  DRIVER: "postgresql+asyncpg"
  ECHO: true